name: testing

on:
  push:
    branches:
      - master
jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: one commit message
        env:
          COMMIT_MESSAGE: ${{ toJson(join(github.event.commits.*.message, ' ')) }}
        run: echo "$COMMIT_MESSAGE"
      - name: contain
        env:
          CONTAINMENT: ${{ toJson(contains(join(github.event.commits.*.message, ' ')), 'skip')}}
        run: echo "$COINTAINMENT"